/* This file is automatically generated by "Resources/Shaders/Examples/UnrollShader/input_no_iterVar.iter_fs". */

void Test()
{
	/*function body*/
}

void NoIterVariable()
{
	/*example for using one loop without any iterate variable*/ 
/*--------------------------------------------------------*/
/* below codes are generated by "unroll_shader" command.*/
	Test();
	Test();
	Test();
/*--------------------------------------------------------*/
}

void main()
{
	NoIterVariable();
}


