/* This file is automatically generated by "Resources/Shaders/Examples/UnrollShader/input_two_same_iterVars.iter_fs". */

void Test()
{
	/*function body*/
}

void TwoSameIterVariables()
{
	/*example for using one loop with two same iterate variables*/ 
/*--------------------------------------------------------*/
/* below codes are generated by "unroll_shader" command.*/
	Test(0.000000, 0.000000);
	Test(1.000000, 1.000000);
	Test(2.000000, 2.000000);
/*--------------------------------------------------------*/
}

void main()
{
	TwoSameIterVariables();
}


